### ISSUE TITLE
Phone numbers should be Strings or VARCHAR

### ISSUE THREAD

**Issue by jonesjsc** [Oldies-but-Goodies/Paperless-Fundraisers#25]
phone number field in the customer table is set to integer, but it's better if this is VARCHAR.  https://stackoverflow.com/questions/24353778/which-is-best-data-type-for-phone-number-in-mysql-and-what-should-java-type-mapp

**Comment by jonesjsc** [comment]
since josh is in there he's gonna change this

**Comment by joshwalters34** [comment]
this is fixed now!
