### ISSUE TITLE
jason's seed.js file where he copied from josh's project 2 needs to be fixed

### ISSUE THREAD

**Issue by jonesjsc** [Oldies-but-Goodies/Paperless-Fundraisers#30]

**Comment by jonesjsc** [comment]
when jason used Josh's seed.js file as a template he failed to catch that the model names needed to be changed what whatever that lame ass golf app thing was to this hella cool project 3 thing with fundraisers and stuff.

**Comment by joshwalters34** [comment]
I got it cleaned up
